export const ADD_PLACE = "ADD_PLACE";
export const DELETE_PLACE = "DELETE_PLACE";
export const ADD_CURRENT_LOCATION = "ADD_CURRENT_LOCATION";
export const ADD_PLACES_TO_DISPLAY_ON_MAP = "ADD_PLACES_TO_DISPLAY_ON_MAP";
export const ADD_USERNAME = "ADD_USERNAME";
export const REMOVE_USERNAME = "REMOVE_USERNAME";
export const ADD_TOKEN = "ADD_TOKEN";
export const REMOVE_TOKEN = "REMOVE_TOKEN";