
export const catData = [
  {id: 1, name: "Music", selected: false},
  {id: 2, name: "Conference", selected: false},
  {id: 3, name: "Comedy", selected: false},
  {id: 4, name: "Learning/Education", selected: false},
  {id: 5, name: "Family/Fun/Kids", selected: false},
  {id: 6, name: "Festivals/Parades", selected: false},
  {id: 7, name: "Movies/Film", selected: false},
  {id: 8, name: "Food", selected: false},
  {id: 9, name: "Fundraisers", selected: false},
  {id: 10, name: "Art", selected: false},
  {id: 11, name: "Support", selected: false},
  {id: 12, name: "Holiday", selected: false},
  {id: 13, name: "Books", selected: false},
  {id: 14, name: "Attractions", selected: false},
  {id: 15, name: "Community", selected: false},
  {id: 16, name: "Business", selected: false},
  {id: 17, name: "Singles/Social", selected: false},
  {id: 18, name: "Schools/Alumni", selected: false},
  {id: 19, name: "Clubs/Associations", selected: false},
  {id: 20, name: "Outdoors/Recreation", selected: false},
  {id: 21, name: "Performing/Arts", selected: false},
  {id: 22, name: "Animals", selected: false},
  {id: 23, name: "Politics/Activism", selected: false},
  {id: 24, name: "Sales", selected: false},
  {id: 25, name: "Science", selected: false},
  {id: 26, name: "Religion/Spirituality", selected: false},
  {id: 27, name: "Sports", selected: false},
  {id: 28, name: "Technology", selected: false},
  {id: 29, name: "Other", selected: false}
];